config/routes.rb
InstaggerWall::Application.routes.draw do
  
  root to: "home#index"
  get "/home", to: "home#index", as: :home
  get "/auth/instagram/callback", to: "users#create"
  get "/auth/signout", to: "sessions#destroy"
  get "/auth/authenticate", to: "sessions#show"
  resources :walls, only: [:new, :create] do
    resources :removed_contents, only: [:index, :create]
  end
  get "/:wall_url", to: "walls#show", as: :wall
  
end

app/models/removed_content.rb
class RemovedContent < ActiveRecord::Base
  
  belongs_to :wall, inverse_of: :removed_contents  
  validates :wall, :content_id, presence: true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  validates :username, :instagram_id, :instagram_token, :instagram_nickname, presence: true
  validates :username, :instagram_id, :instagram_nickname, uniqueness: true
  
  has_many :walls, inverse_of: :user
  
end

app/models/wall.rb
require "base62"
class Wall < ActiveRecord::Base
  
  belongs_to :user, inverse_of: :walls
  has_many :removed_contents, inverse_of: :wall, dependent: :destroy
  
  validates :user, :hashtag, presence: true
  validates :hashtag, uniqueness: true
  validates :hashtag, length: { in: 4..30 }
  validates :hashtag, format: /\A[a-zA-z0-9]+\z/
  
  after_create :generate_url
  
  def self.find_by_url(wall_url)
    find_by(url: "#{wall_url.base62_decode}")
  end
  
  def generate_url
    update_attribute(:url, "#{self.id.base62_encode}")
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include Cryptor
  protect_from_forgery with: :exception
  
  def sign_in(user)
    cookies[:user_token] = { value: encrypt_string(user.id) } 
  end
  
  def sign_out
    cookies.delete :user_token
  end
  
  def current_user
    @current_user ||= User.find(decrypt_string(cookies[:user_token])) if cookies[:user_token].present?
  end
  helper_method :current_user
  
  def authenticate_user!
    redirect_to root_path unless current_user
  end
  
end

app/controllers/concerns/cryptor.rb
module Cryptor
  
  def encryptor
    secret = "aWTvbXMhZCBvhW1kc2FvaSBtZGFzb2kaZG1hc29pZG0gYXNvaWRtIG9haXNkbSBhZA=="
    ActiveSupport::MessageEncryptor.new(secret)
  end
  
  def encrypt_string(string)
    encryptor.encrypt_and_sign(string)
  end
  
  def decrypt_string(string)
    encryptor.decrypt_and_verify(string) rescue nil
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    redirect_to new_wall_path if current_user
  end
  
end

app/controllers/removed_contents_controller.rb
class RemovedContentsController < ApplicationController
  
  before_action :load_wall
  
  def index
    respond_to do |format|
      format.json {
        render json: @wall.removed_contents.all
      }
    end
  end
  
  def create
    @removed_content = @wall.removed_contents.create(removed_content_params)
    respond_to do |format|
      format.js
    end
  end
  
  private
  
  def load_wall
    @wall = current_user.walls.find(params[:wall_id])
  end
  
  def removed_content_params
    params.require(:removed_content).permit(:content_id)
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def show
    respond_to do |format|
      format.json {
        render json: { id: current_user.try(:id) }
      }
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def create
    auth = request.env["omniauth.auth"]
    @user = User.find_or_create_by({
      username: auth["info"]["nickname"],
      instagram_id: auth["uid"],
      instagram_token: auth["credentials"]["token"],
      instagram_nickname: auth["info"]["nickname"],
      instagram_image: auth["info"]["image"]
    })
    if @user.persisted?
      sign_in(@user)
      redirect_to new_wall_path
    else
      redirect_to root_path
    end
  end
  
  def omniauth_failure
    if params[:error_reason] === "user_denied"
      flash[:notice] = "You must authorize our app to access your Instagram account"
    end
    redirect_to roo_path
  end
  
end

app/controllers/walls_controller.rb
class WallsController < ApplicationController
  
  before_action :authenticate_user!, only: [:new, :create]
  
  def new
    @walls = current_user.walls
    @wall = current_user.walls.new
  end
  
  def create
    @wall = current_user.walls.create(wall_params)
    respond_to do |format|
      format.js {
        @wall.reload if @wall.persisted?
      }
    end
  end
  
  def show
    @wall = Wall.find_by(url: params[:wall_url])
    @pagetitle = "Instagger Wall ##{@wall.hashtag}"
    @pagedescription = "Invite your friends or take a picture!"
    redirect_to root_path unless @wall
  end
  
  protected
  
  def wall_params
    params.require(:wall).permit(:hashtag)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def icon_tag(icon, content = nil)
    content_tag(:span, nil, class: "glyphicon #{icon}") + " #{content}"
  end
  
end

app/views/home/index.html.erb
<div class="container home">
  <div class="row">
    <div class="col-sm-12">
      <h1>Instagger Wall</h1>
      <p class="help-block">Create a photo wall with your friends using Instagram.</p>
      <p><%= link_to "Login with Instagram", "/auth/instagram", class: "btn btn-lg" %></p>
    </div>
  </div>
</div>
<div class="container home-footer">
  <div class="row">
    <div class="col-sm-12">
      <%= link_to "About", "#about", class: "about" %>
      <%= link_to "Want a Instagram blog?", "http://www.instagger.com", class: "instagger-blog" %>
      <%= link_to "Privacy Policy", "#privacy-policy", class: "privacy-policy" %>
    </div>
  </div>
</div>
<div class="modal fade" id="modal-privacy-policy" tabindex="-1" role="dialog" aria-labelledby="privacy-policy" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="privacy-policy">Privacy policy</h4>
      </div>
      <div class="modal-body">
        <p>Instagger Wall will only collect your personal information when you voluntarily sign-up for a membership account. Information collected from you will never be sold, rented, or shared with third-parties.</p>
        <p>The website utilizes "cookies". A "cookie" is a small text file that permits us to recognize your browser in order to customize your experience, or permit you to access restricted areas. Cookies do not contain personal information.</p>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="modal-about" tabindex="-1" role="dialog" aria-labelledby="about" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="about">About</h4>
      </div>
      <div class="modal-body">
        <p>With Instagger Wall you can invite your friends to take pictures with you using Instagram and
          create a photo wall. You can easily remove photos that you don't want from your photo wall.</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @pagetitle || 'Instagger Wall' %></title>
    <meta content="<%= @pagedescription || 'With Instagger Wall you can invite your friends to take pictures with you using Instagram and create a photo wall. You can easily remove photos that you don\'t want from your photo wall.' %>" name="description" />
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-46109774-2', 'instagger.com');
      ga('send', 'pageview');
    </script>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/removed_contents/create.js.erb
<% if @removed_content.persisted? %>
  $(".wall ul.holder > li#photo-<%= @removed_content.content_id %>").fadeOut("fast", function(){
    $(this).remove();
  });
<% else %>
  alert("<%= j @removed_content.errors.full_messages.join(", ") %>")
<% end %>

app/views/shared/_header.html.erb
<header>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 clearfix">
        <h1><%= @wall.persisted? ? "##{@wall.hashtag}" : "Instagger Wall" %></h1>
        <div class="btn-group pull-right">
          <%= link_to icon_tag("glyphicon-home"), root_path, class: "btn btn-sm" %>
        </btn>
      </div>
    </div>
  </div>
</header>

app/views/walls/create.js.erb
<% if @wall.persisted? %>
  window.location.href = "<%= wall_path(@wall.url) %>";
<% else %>
  alert("<%= j @wall.errors.full_messages.join(", ") %>")
<% end %>

app/views/walls/new.html.erb
<%= render "shared/header" %>
<div class="container create-wall">
  <div class="row">
    <div class="col-sm-12">
      <h1>Create your photo wall</h1>
      <%= form_for @wall, html: { data: {remote: true}} do |f| %>
        <%= f.text_field :hashtag, class: "form-control input-lg", placeholder: "#weddingjohnandlara, #party20131201ellen" %>
      <% end %>
      <p class="help-block">When you create a photo wall with a tag, all Instagram media that have this tag will
        appear in your wall. Remember to use not common terms if you want your wall only
        with your and friend's photos and videos.</p>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <ul class="user-walls">
        <% @walls.each do |user_wall| %>
          <% if user_wall.url %>
            <li><%= link_to "##{user_wall.hashtag}", wall_path(user_wall.url) %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/walls/show.html.erb
<%= render "shared/header" %>
<div class="container">
  <div class="row">
    <section class="wall">
      <div class="empty-wall">
        <p class="reload"><%= link_to icon_tag("glyphicon-refresh"), wall_path(@wall.url), class: "btn" %></p>
        <h2>Invite your friends or take a picture!</h2>
        <p>Ask your friends to take pictures and include de hashtag <strong>#<%= @wall.hashtag %></strong>.</p>
      </div>
      <ul class="holder clearfix">
      </ul>
    </section>
  </div>
</div>
<%= hidden_field_tag :wall_id, @wall.id %>
<%= hidden_field_tag :tag, @wall.hashtag %>
<%= hidden_field_tag :token, @wall.user.instagram_token %>
<%= hidden_field_tag :removed_content, @wall.removed_contents.collect { |r| r.content_id }.join(",") %>